<a href='http://utiva.org'><h2> PYTHON FOR DATA-SCIENCE</a>
___

# Ecommerce Purchases Exercise

In this Exercise you will be given some Fake Data about some purchases done through Amazon! Just go ahead and follow the directions and try your best to answer the questions and complete the tasks. Feel free to reference the solutions. Most of the tasks can be solved in different ways. For the most part, the questions get progressively harder.

Please excuse anything that doesn't make "Real-World" sense in the dataframe, all the data is fake and made-up.

Also note that all of these questions can be answered with one line of code.
____
** Import pandas and read in the Ecommerce Purchases csv file and set it to a DataFrame called ecom. **

In [3]:
import pandas as pd
import numpy as np

In [4]:
ecomm = pd.read_csv('Ecommerce Purchases.csv')

**Check the head of the DataFrame.**

In [10]:
ecomm.head(3)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95

** How many rows and columns are there? **

In [8]:
## TO FIND THE NUMBER OF ROWS AND COLUMNS WE WILL RUN THE DATA SET BY TYPING "ecomm" IN THE NEXT LINE BELOW

ecomm

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [17]:
## THERE ARE 10000 ROWS AND 14 COLUMNS

In [19]:
## TO HAVE AN OVERVIEW OF THE NUMBER OF ITEMS IN EACH COLUMN IN THE DATA FRAME, WE USE THE "nunique()" METHOD

ecomm.nunique()

Address             10000
Lot                  9822
AM or PM                2
Browser Info         8287
Company              8653
Credit Card         10000
CC Exp Date           121
CC Security Code     1758
CC Provider            10
Email                9954
Job                   623
IP Address          10000
Language                9
Purchase Price       6349
dtype: int64

# QUESTION 1

** What is the average Purchase Price? **

In [18]:
## TO FIND THE AVERAGE PURCHASE PRICE OF THE VALUES IN THE COLUMN CALLED "PURCHASE PRICE", WE WILL USE THE MEAN FUNCTION
## AND CALL IT ON THE "Purchase Price" DATAFRAME. 

ecomm["Purchase Price"].mean()

50.34730200000025

In [21]:
# THE AVERAGE PURCHASE PRICE IS 50.34730200000025

# QUESTION 2

** What were the highest and lowest purchase prices? **

In [23]:
## TO FIND THE MAXIMUM/HIGHEST PRICE OF THE VALUES IN THE COLUMN CALLED "PURCHASE PRICE", WE WILL USE THE "Max" FUNCTION
## AND CALL IT ON THE "Purchase Price" DATAFRAME.

ecomm["Purchase Price"].max()

99.99

In [24]:
## TO FIND THE MINIMUM/LOWEST PRICE OF THE VALUES IN THE COLUMN CALLED "PURCHASE PRICE", WE WILL USE THE "Min" FUNCTION
## AND CALL IT ON THE "Purchase Price" DATAFRAME.

ecomm["Purchase Price"].min()

0.0

In [92]:
## The Highest and Lowest values of in the "Purchase Price" Column are 99.99 and 0.0 respectively

99.989999999999995

# QUESTION 3

** How many people have English 'en' as their Language of choice on the website? **

In [27]:
## TO SOLVE THIS CHALLLENGE, WE SHALL WRITE CODE TO DETEMINE BINARY VALUES FOR PEROPLE WHO HAVE ËNGLISH "en" AS CHOICE LANGUAGE

ecomm['Language'] == 'en'

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: Language, Length: 10000, dtype: bool

In [26]:
## AFTER DETERMINING THE BINARY VALUES, WE SHALL USE THE "Count" FUNCTION TO COUNT NUMBER OF PEOPLE THAT ENGLISH "en" AS 
## LANGUAGE OF CHOICE

ecomm[ecomm['Language'] == 'en'].count()

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64

In [29]:
# THE NUMBER OF NUMBER THAT HAVE "en" AS LANGUAGE OF CHOICE UNDER "LANGUAGE" COLUMN ARE 1098

# QUESTION 4

** How many people have the job title of "Lawyer" ? **

In [31]:
## TO SOLVE THIS CHALLENGE, WE CAN USE TWO(2) METHODS, THE FIRST METHOD IS TO SUM UP THE EXACT NUMBER OF TIMES THE WORD
## LAWYER WAS RECORDED IN THE COLUMN "Job" IN THE DATA FRAME

sum (ecomm["Job"] == "Lawyer")

30

In [34]:
# METHOD 2 - WE SHALL USE THE "Count" FUNCTION TO COUNT NUMBER OF PEOPLE THAT THE WORD "LAWYER" WAS REFERENCED IN THE DATA FRAME 
ecomm[ecomm['Job'] == "Lawyer"].count()

Address             30
Lot                 30
AM or PM            30
Browser Info        30
Company             30
Credit Card         30
CC Exp Date         30
CC Security Code    30
CC Provider         30
Email               30
Job                 30
IP Address          30
Language            30
Purchase Price      30
dtype: int64

In [35]:
## the number of people with Job title of Laywer are "30"

# QUESTION 5

** How many people made the purchase during the AM and how many people made the purchase during PM ? **

**(Hint: Check out [value_counts()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html) ) **

In [51]:
## TO SOLVE THIS CHALLENGE, WE SHALL GROUP ALL THE UNIQUE VALUES IN THE COLUMN CALLED "AM or PM". THEREAFTER, WE SHALL USE
## THE "Value.Counts()" FUNCTION TO COUNT THE TOTAL GROUPED VALUES

ecomm["AM or PM"].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [ ]:
# THE NUMBER OF PEOPLE WHO MADE PURCHASE AT "AM" ARE 4932 WHILE THE NUMBER WHO MADE PURCHASE AT "PM" ARE 5068

# QUESTION 6

** What are the 5 most common Job Titles? **

In [53]:
## TO SOLVE THIS CHALLENGE, FIRSTLY WE WILL FIND THE NUMBER OF UNIQUE JOB TITLES IN THE COLUMN CALLED "Job" BY USING THE 
## "Value.Counts()" FUNCTION

ecomm["Job"].value_counts()

Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Purchasing manager                   27
Research officer, political party    27
                                     ..
Special effects artist                7
Actuary                               6
Editor, film/video                    6
Investment analyst                    5
Information systems manager           5
Name: Job, Length: 623, dtype: int64

In [56]:
## SECONDLY WE SHALL APPLY THE "head()" FUNCTION AND LIMIT THE LIST TO THE TOP FIVE(5) MOST COMMON JOB TITLES

ecomm["Job"].value_counts().head(5)

Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Purchasing manager                   27
Research officer, political party    27
Name: Job, dtype: int64

# QUESTION 7

** Someone made a purchase that came from Lot: "90 WT" , what was the Purchase Price for this transaction? **

In [60]:
ecomm.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14

In [64]:
## TO SOLVE THIS CHALLENGE, WE SHALL APPLY CONDITIONAL STATEMENT TO FILTER THE DATA. WE SHALL FILTER COLUMN "Lot" ON THE
## VALUE "90 WT" and use the "and(&)" FUNCTION TO FILTER THE "Purchase Price" COLUMN TO FIND THE PURCHASE PRICE OF LOT 90 WT

ecomm[(ecomm["Lot"] == "90 WT") & (ecomm['Purchase Price'])]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
513,"50398 Mccoy Rest Suite 597\nSouth Garyborough,...",90 WT,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_2 like M...,Bright PLC,630438419693,11/19,173,American Express,jesse00@page.net,Energy engineer,156.70.208.94,ru,75.1

In [ ]:
# THE PURCHASE PRICE FOR LOT "90 WT" IS 75.1

# QUESTION 8

** What is the email of the person with the following Credit Card Number: 4926535242672853 **

In [79]:
## TO SOLVE THIS CHALLENGE, WE SHALL ADOPT THE SAME THOUGHT PROCESS WE APPLIED IN QUESTION 7. 
## WE SHALL APPLY CONDITIONAL STATEMENT TO FILTER THE DATA. WE SHALL FILTER COLUMN "Credit Card" WITH NUMBER "4926535242672853"
## and use the "and(&)" FUNCTION TO FILTER THE "Email" COLUMN TO FIND THE EMAIL OF CREDIT CARD NUMBER MENTIONED ABOVE

ecomm[(ecomm["Credit Card"] == 4926535242672853) & (ecomm['Email'])]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1234,"2470 Maria Manors Suite 185\nJoneshaven, MN 87251",82 UX,PM,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.5.20) G...,"Cole, King and Bowers",4926535242672853,09/21,188,American Express,bondellen@williams-garza.com,Planning and development surveyor,159.182.3.50,ru,77.88

In [80]:
# THE EMAIL ADDRESS OF CREDIT CARD NUMBER 4926535242672853 IS bondellen@williams-garza.com

# QUESTION 9

** How many people have American Express as their Credit Card Provider *and* made a purchase above $95 ?**

In [83]:
## TO SOLVE THIS CHALLENGE, WE SHALL APPLY A SMILAR THOUGH PROCESS TO QUESTION 7 AND 8.
## WE SHALL APPLY CONDITIONAL STATEMENT TO FILTER THE DATA. WE SHALL FILTER Credit Card Provider COLUMNT WITH "American Express"
## and THEREAFTER USE THE "and(&)" FUNCTION TO FILTER THE "Purchase Price" COLUMN WITH PURCHASES ABOVE $95


ecomm[(ecomm["CC Provider"] == "American Express") & (ecomm['Purchase Price'] > 95)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63
280,81060 Dustin Causeway Apt. 503\nPort Danielche...,80 zh,PM,Mozilla/5.0 (Windows NT 5.01) AppleWebKit/5362...,Clay PLC,377737470673585,10/17,349,American Express,hfarley@hicks.com,Ergonomist,134.52.148.32,de,99.13
372,"359 Stanley Coves\nSalasfort, SD 59457",75 Ub,PM,Opera/8.42.(X11; Linux x86_64; en-US) Presto/2...,Davis-Lawrence,371995567939253,02/26,1877,American Express,amberhull@jones.net,Training and development officer,198.98.34.250,pt,99.08
677,"4855 Peter Bridge\nJohnsonberg, PA 90599-0009",62 Nx,AM,Opera/9.49.(Windows 98; Win 9x 4.90; en-US) Pr...,Jones and Sons,4960556611626434,07/26,9255,American Express,evanskayla@fernandez.com,Plant breeder/geneticist,235.97.240.112,el,98.97
766,"386 Alisha Unions\nSteelebury, ND 19782",28 pJ,PM,Opera/8.47.(X11; Linux x86_64; sl-SI) Presto/2...,Proctor PLC,30325623350308,04/24,772,American Express,robertsonjulia@gmail.com,"Therapist, art",146.208.30.83,es,96.66
1225,"916 Amanda Heights\nNew Johnland, CA 52112-8572",09 vg,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Clark, Ross and Travis",371229555854245,10/21,366,American Express,lawrencecarter@kelly.com,Artist,88.49.59.205,pt,96.55
1381,"79284 Lisa Mews Suite 069\nKellyborough, CT 71...",45 MR,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_5_5; r...,Randall-Cohen,4855262855037,05/17,518,American Express,maldonadomichael@martinez-delgado.info,Geophysical data processor,50.40.147.204,it,96.11
1385,"67796 James Keys Suite 656\nSouth Katieshire, ...",06 ia,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5330 ...,"Gonzalez, Gross and Allen",30407332938506,12/20,597,American Express,vbrown@daugherty.com,Geophysical data processor,152.133.246.191,zh,98.89
1568,"76108 Barker Manors\nEast Amy, PW 49544-5921",82 Qw,AM,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,"Nguyen, Branch and Wiley",5142451859832464,04/21,785,American Express,johnsonjulie@yahoo.com,Insurance claims handler,175.248.232.126,es,97.04
1727,"478 Anita Hill Apt. 766\nAverymouth, FM 50629-...",94 qM,AM,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,Owen and Sons,30242757909967,11/19,7403,American Express,sharpmelanie@smith-johnson.com,"Psychologist, prison and probation services",126.47.196.22,ru,95.58
2146,"557 Barton Harbor\nFuentesport, VI 29961",96 MV,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows 98;...,Flores-Cook,3337255995040373,04/19,28,American Express,jessica94@mosley-buchanan.com,Armed forces technical officer,35.97.189.19,es,98.01
2264,"040 Ingram Way Suite 602\nEast Matthew, AR 67341",52 WA,AM,Mozilla/5.0 (Windows NT 6.0) AppleWebKit/5341 ...,"Baker, Simmons and Pitts",3096946456575623,11/22,56,American Express,holtamanda@gmail.com,Archaeologist,185.14.106.115,es,99.85
2267,"216 Olivia Court Apt. 439\nTonyshire, IN 19159...",11 za,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_4; r...,Olson Inc,5388757330269354,02/17,738,American Express,burkestephanie@lee-cameron.com,Management consultant,20.140.16.225,it,97.63
2642,899 Williams Prairie Suite 234\nEast Hunterbur...,46 hb,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Webb Inc,3096797127305092,05/17,418,American Express,reevesmanuel@gmail.com,"Engineer, maintenance (IT)",169.132.152.152,el,96.08
2828,"20135 Miller Green Apt. 763\nGarciaville, KY 6...",79 El,PM,Mozilla/5.0 (Windows; U; Windows CE) AppleWebK...,"Zavala, Cox and Parker",5173968976288215,11/22,125,American Express,villarrealdavid@gray.com,Chartered management accountant,76.75.229.58,el,96.12
3291,"58939 Reese Cove\nSouth Ross, MA 54531",50 cD,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows 95;...,"Chang, Davis and Snyder",349464844934636,11/23,103,American Express,stephanieacosta@yahoo.com,IT trainer,124.247.101.106,it,95.94
3349,1984 Christopher Turnpike Suite 904\nRichardbu...,30 xs,AM,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...,Martin-Mitchell,3096398727024637,03/19,439,American Express,hgross@mccoy-mckay.info,Structural engineer,167.172.139.33,pt,95.46
3619,"03233 Angela Road Apt. 808\nEast Jilliantown, ...",41 nH,PM,Opera/9.53.(Windows 95; en-US) Presto/2.9.175 ...,"Silva, Kim and Martinez",4807251488895729,10/21,948,American Express,jonesjesse@castro.info,Garment/textile technologist,87.66.16.4,en,99.69
4071,"8161 Craig Passage Apt. 939\nPort Emilystad, R...",45 ab,AM,Mozilla/5.0 (Windows; U; Windows NT 6.1) Apple...,Wilson-Robinson,5506767693718324,08/23,18,American Express,hhenderson@yahoo.com,Customer service manager,119.74.76.168,es,96.49
4569,"88284 Austin Summit Apt. 805\nKellerside, WY 6...",03 WL,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_5...,"Fisher, Thompson and Lynch",3088726880694574,12/19,159,American Express,amy00@patton.com,Actuary,207.18.223.8,el,97.38
5385,USNS Smith\nFPO AA 37829,80 BX,AM,Opera/9.56.(X11; Linux x86_64; en-US) Presto/2...,Patterson-Miller,4411786056713950,12/22,452,American Express,ijones@hotmail.com,Field seismologist,251.254.250.100,el,96.13
5655,"38674 Mckay Vista\nWilsonbury, MO 55611-8663",95 aB,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5331...,Watson-Bailey,3096820981608615,05/20,259,American Express,timothy84@hotmail.com,"Production designer, theatre/television/film",235.149.102.129,es,98.28
5692,"PSC 8264, Box 8124\nAPO AE 19700",97 sG,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,Moore Inc,6011499701167585,10/20,845,American Express,kellypace@yahoo.com,Aid worker,155.121.60.58,pt,98.66
5814,Unit 5232 Box 4650\nDPO AE 28335-7543,71 So,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5342...,Garcia LLC,30346960979608,07/17,402,American Express,jrice@gmail.com,Solicitor,165.48.161.188,zh,96.73
5875,"8256 Anderson Forest\nFordbury, PA 81027-8980",17 Oe,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Kelly, Peterson and Oliver",5173335726386576,02/18,954,American Express,hernandezandrea@yahoo.com,Community development worker,212.168.246.27,ru,95.07
5895,"87003 Jason Tunnel Apt. 216\nDariusville, MS 8...",72 gL,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Reyes, Fox and Wilson",180010957603245,09/24,929,American Express,duncanmichael@hotmail.com,Event organiser,231.34.199.32,it,97.38
6026,Unit 4385 Box 1428\nDPO AE 04110,58 Ex,AM,Mozilla/5.0 (Windows; U; Windows NT 5.01) Appl...,White Inc,3112975578138572,09/17,7,American Express,scott35@yahoo.com,Operations geologist,217.6.202.138,en,95.89
6524,"344 Rivera Shore Apt. 224\nJoshuaborough, ND 3...",44 SM,AM,Opera/8.62.(X11; Linux i686; en-US) Presto/2.9...,"Lawson, Moyer and Valencia",379348662534664,06/17,809,American Express,olsonjohn@hotmail.com,"Teacher, primary school",45.1.104.55,zh,97.87
7239,"81561 Stein Rue\nEast Melissaport, MA 64959",45 sZ,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5310...,Smith Ltd,503825682670,07/19,852,American Express,beckerjennifer@gmail.com,"Engineer, energy",50.107.135.203,fr,97.32
7381,"40804 Belinda Roads Apt. 186\nWest Nicoleberg,...",30 GH,AM,Opera/9.32.(Windows NT 4.0; it-IT) Presto/2.9....,Blair-Keith,180089858618619,05/19,2107,American Express,woodsmatthew@walton.org,Fashion designer,223.87.136.82,es,99.81
7416,"1082 Jason Alley Suite 707\nWhitestad, SC 97805",08 bm,PM,Mozilla/5.0 (Windows NT 5.1; sl-SI; rv:1.9.2.2...,"Carroll, Harrison and Escobar",3088903707645291,12/18,220,American Express,gcruz@butler.com,Broadcast presenter,193.90.91.152,pt,96.09
7514,"678 David Manor Suite 323\nBobbymouth, PW 59942",91 NA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows 98;...,"Glenn, Lowe and Shah",676298897445,04/26,61,American Express,tammy75@cameron.com,Automotive engineer,37.241.180.247,ru,98.36
8233,"327 Hamilton Hollow\nEast Nicolechester, RI 65868",53 dE,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_3...,"Keller, Carter and Garcia",30299608736429,08/22,786,American Express,elliskaren@taylor.com,Chemical engineer,131.34.220.138,en,98.63
8381,"274 Wallace Pine Apt. 189\nMartinberg, WY 7548...",32 rI,PM,Mozilla/5.0 (Windows; U; Windows 98; Win 9x 4....,Kelly-Newman,5527104423944290,05/18,711,American Express,joneswilliam@cox.net,"Surveyor, land/geomatics",29.211.114.191,ru,99.36
8408,Unit 4967 Box 4574\nDPO AP 11412,05 zs,PM,Mozilla/5.0 (compatible; MSIE 5.0; Windows 98;...,Acevedo-Smith,3337721305744244,01/19,738,American Express,nunezjames@hotmail.com,"Designer, exhibition/display",91.55.254.144,es,98.16
8434,"474 Gonzalez Meadow Suite 581\nEast Vincent, M...",14 St,PM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Miller and Sons,180059754370698,07/24,812,American Express,vtaylor@hatfield.com,Armed forces technical officer,26.69.128.20,it,97.90
8817,"3658 Campos Lodge\nChambersfurt, MH 86260",24 ej,PM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Fisher-Jones,210046575239925,09/25,860,American Express,jessica35@hotmail.com,Forensic scientist,18.74.143.113,fr,99.16
9168,"18782 Hall Row Suite 810\nSouth Wesleyville, I...",15 QU,PM,Opera/9.57.(X11; Linux i686; it-IT) Presto/2.9...,Butler PLC,5412611065926441,05/25,49,American Express,tammyblair@yahoo.com,Computer games developer,2.84.51.133,en,98.59
9856,"058 Miranda Locks Suite 792\nPort Davidstad, P...",73 IW,PM,Mozilla/5.0 (Windows NT 5.0) AppleWebKit/5360 ...,Olson-Navarro,6011037226242937,03/18,757,American Express,brendastewart@dalton.info,Site engineer,96.79.250.154,de,99.97

In [85]:
## TO FIND THE EXACT NUMBER OF PEOPLE WHO MET CONDTION ABOVE, WE SHALL APPLY THE "Count" FUNCTION TO COUNT THE DATA
    
ecomm[(ecomm["CC Provider"] == "American Express") & (ecomm['Purchase Price'] > 95)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

In [86]:
## THERE ARE 39 PEOPLE WHO USED "AMERICAN EXPRESS" AS CREDIT CARD PROVIDE AND MAKE PURCHASES ABOVE $95

# QUESTION 10

** Hard: How many people have a credit card that expires in 2025? **

In [89]:
## before we solve the challenge, we shall take a look at how the expiry date is defined in the "CC Expiry Date" Column below

ecomm.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14

In [100]:
## WE WONT BE ABLE TO FILTER THE DATA TO DERIVE ACCURATELY THE YEAR OF THE EXPIRY DATE BECAUSE OF HOW THE EXPIRY DATE IS DEFINED
## SO WE SHALL WRITE A FUNCTION THAT WILL EXTRACT THE LAST 2 DIGITS OF THE EXPIRY DATE. FOR EXAMPLE "02/20" WILL BE EXTRACTED
## AND THE RESULT WILL BE "20" WHICH MEANS THE YEAR OF THE EXPIRY DATE IS 2020

## FUNCTION
def exp_date(x):
    x = list(x)      #CONVERT THE DATE TO A LIST AND STORE IN VARIABLE X
    x = x[3] + x[4]  #CONCATENATE INDEX 3 AND 4 OF THE LIST TO FORM A SINGLE STRING AND STORE IN VARIABLE X
    x = int(x)       #CONVERT THE VARIABLE INTO AN INTEGER AND STORE IN X
    return x

In [103]:
# NEXT STEP, WE SHALL CREATE A NEW COLUMN CALLED "new_exp_date" ON OUR DATA FRAME AND APPLY THE LAMBDA FUNCTION ON "exp_date(x)"
# INSIDE THE NEW COLUMN WHICH IS TO BE CREATED

ecomm["new_exp_date"] = ecomm["CC Exp Date"].apply(lambda x: exp_date(x))

In [104]:
# THE NEW COLUMN "new_exp_date" is the last column on the Data Frame 

ecomm.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,new_exp_date
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,20

In [109]:
## TO FIND THE NUMBER OF PEOPLE WHOSE CREDIT WILL EXPIRE IN 2025, WE SHALL FILTER THE "new_exp_date" column on the Year "25".
## THEREAFTER WE SHALL APPLY THE COUNT "Sum()" FUNCTION

sum(ecomm["new_exp_date"] == 25)

1033

In [111]:
## There are 1033 people whose credit card have expiry date of 2025

# QUESTION 11

** Hard: What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...) **

In [116]:
ecomm.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,new_exp_date
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,20

In [114]:
# TO BEGIN THIS CHALLENGE, WE WILL HAVE TO CONVERT THE EMAIL ADDRESSES "AAA@yahoo.com" TO THIER HOST NAMES "yahoo.com"
# IN ORDER TO ACHIEVE THIS, WE SHALL WRITE A FUNCTION THAT WILL REMOVE THE EMAIL NAME AND RETURN ONLY THE HOST NAME "Yahoo.com"

def domain_name(x):
    x = x.split('@')      #Split the string when it gets to the word "@"
    x = x[1]              #return index 1 and store in variable x
    x = str(x)            #Convert the list to a string and store in x
    return x

In [117]:
domain_name("seun@yahoo.com") # This is to test if our function returns the right result we intend for it to return

'yahoo.com'

In [119]:
# NEXT STEP, WE SHALL CREATE A NEW COLUMN CALLED "new_domain_name" ON OUR DATA FRAME AND APPLY THE LAMBDA FUNCTION ON 
# THE ACTUAL FUNCTION "domain_name(x)" INSIDE THE NEW COLUMN WHICH IS TO BE CREATED

ecomm["new_domain_name"] = ecomm["Email"].apply(lambda x: domain_name(x))

In [121]:
# The NEW COLUMN CALLED "new_domain_name" IS THE LAST COLUMN ON THE DATA FRAM BELOW

ecomm.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,new_exp_date,new_domain_name
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,20,yahoo.com

In [123]:
# TO SOLVE THE CHALLENGE, FIRSTLY, WE SHALL DETERMINE THE NUMBER OF TIMES THE HOST NAMES IN THE "new_domain_name" COLUMN OCCURED
# BY USING THE "value_counts()" FUNCTION

ecomm["new_domain_name"].value_counts()

hotmail.com         1638
yahoo.com           1616
gmail.com           1605
smith.com             42
williams.com          37
                    ...
page.net               1
vasquez-luna.com       1
newton.com             1
yu-miranda.org         1
klein.net              1
Name: new_domain_name, Length: 3416, dtype: int64

In [124]:
# NEXT, WE SHALL DETERMINE THE TOP FIVE(5) HOST NAMES BY USING THE "head()" function

ecomm["new_domain_name"].value_counts().head(5)

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: new_domain_name, dtype: int64